<<<<<<< HEAD
image: node:6.10.0

stages:
  - push_to_packman_staging

push_to_packman_staging:
  stage: push_to_packman_staging
  only:
    - tags
  script:
    - curl -u $USER_NAME:$API_KEY https://staging-packages.unity.com/auth > .npmrc
    - npm publish
=======
image: node:6.10.0

stages:
  - push_to_packman_staging

push_to_packman_staging:
  stage: push_to_packman_staging
  only:
    - tags
  script:
    - curl -u $USER_NAME:$API_KEY https://staging-packages.unity.com/auth > .npmrc
    - npm publish
>>>>>>> 7e9cc7564d17352c33f6ea8482525655190ffcea
